substitutions:
  _ENVIRONMENT: 'dev'
  _VERSION: '1.0'

steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/docker-build-test2:${_ENVIRONMENT}-${_VERSION}', '.' ]
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/docker-build-test2:${_ENVIRONMENT}-${_VERSION}']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'docker-build-test2'
  - '--image'
  - 'gcr.io/$PROJECT_ID/docker-build-test2:${_ENVIRONMENT}-${_VERSION}'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--cpu'
  - '1'
  - '--min-instances'
  - '1'
  - '--max-instances'
  - '1'
  - '--memory'
  - '512m'
images:
- 'gcr.io/$PROJECT_ID/docker-build-test2:${_ENVIRONMENT}-${_VERSION}'
