steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: [ 'build', '-t', 'gcr.io/rapsodoo-test/docker-build-test2:$COMMIT_SHA', '.' ]
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/rapsodoo-test/docker-build-test2:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'docker-build-test2'
   - '--image'
   - 'gcr.io/rapsodoo-test/docker-build-test2:$COMMIT_SHA'
   - '--region'
   - 'europe-west1-b'
   - '--platform'
   - 'managed'
 images:
 - 'gcr.io/rapsodoo-test/docker-build-test2:$COMMIT_SHA'
